### ISSUE TITLE
References

### ISSUE THREAD

**Issue by mdozmorov** [LTLA/TENxBrainAnalysis#1]
Is there a reference associated with this analysis? And/or, with the dataset at https://support.10xgenomics.com/single-cell-gene-expression/datasets? PubMed and Google give nothing, and nothing is in the "scater" paper.

Thanks, @LTLA,
Mikhail

**Comment by LTLA** [comment]
The closest thing is the paper that these scripts were spun-off from:

https://github.com/LTLA/MatrixEval2017
https://www.biorxiv.org/content/early/2017/07/24/167445

... though the idea with this repository is to take this analysis to the next level.

**Comment by mdozmorov** [comment]
Thanks, @LTLA, I overlooked the "beachmat" preprint. Will look into it, and learn the MatrixEval repository. It may be worth putting those links in the README.

Mikhail
